// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjtG28fnl7si0DIs2MXHfV4FjEU9ZADE',
    appId: '1:827618599469:web:3f4bd4474c62dfb4becea4',
    messagingSenderId: '827618599469',
    projectId: 'store-app-95614',
    authDomain: 'store-app-95614.firebaseapp.com',
    storageBucket: 'store-app-95614.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd-7ZleXI-wI5tkf-ws6_HQdpotvvog0A',
    appId: '1:827618599469:android:0a088523f52de5a3becea4',
    messagingSenderId: '827618599469',
    projectId: 'store-app-95614',
    storageBucket: 'store-app-95614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgd1dVtQ8kvhyQZoZeWf6OJG4qYgvnxPQ',
    appId: '1:827618599469:ios:a64ca882f047ca46becea4',
    messagingSenderId: '827618599469',
    projectId: 'store-app-95614',
    storageBucket: 'store-app-95614.firebasestorage.app',
    iosBundleId: 'com.example.macStoreApp',
  );
}
